name = "r8r-platform"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "r8r-platform-db"
database_id = "e278441a-734f-46b6-ac48-72d2d02c6cbc" 