name = "burrito-backup-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "4467ef47f4344bb87ee9fc681c6ca144"

# Run backup every day at midnight UTC
[triggers]
crons = ["0 0 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "burrito-rater-db"
database_id = "0e87da0b-9043-44f4-8782-3ee0c9fd6553"

[[r2_buckets]]
binding = "BACKUP_BUCKET"
bucket_name = "burrito-backup" 